apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "incore.name" . }}
data:
  quota.json: |
    {{- .Values.quota | nindent 4 }}
  ga_key.json: |
    {
      "GA_KEY": "{{- .Values.google_analytics }}"
    }
  auth_config.json: |
    {
      "logoutUrl": {{ .Values.auth.logoutUrl | default "" | quote }}
    }
